<?php
class Dtn_Weblog_Model_Resource_Setup extends Mage_Core_Model_Resource_Setup
{
    function startSetup()
    {
        $this->getConnection()->startSetup();
        return $this;
//        return parent::startSetup(); // TODO: Change the autogenerated stub
    }

    function endSetup()
    {
        $this->getConnection()->endSetup();
//        return parent::endSetup(); // TODO: Change the autogenerated stub
    }
}