<?php

class Dtn_Weblog_Block_Adminhtml_Blogpost_Edit extends Mage_Adminhtml_Block_Widget_Form_Container
{
    public function __construct()
    {
        parent::__construct();
        $this->_objectId = 'id';
        $this->_blockGroup = 'weblog';
        $this->_controller = 'adminhtml_blogpost';

        $this->updateButton('save', 'label', Mage::helper('weblog')->__('Save'));
        $this->updateButton('delete', 'label', Mage::helper('weblog')->__('Delete'));

        $this->addButton('saveandcontinue', array(
            'label'=>Mage::helper('weblog')->__('Save And Continue Edit'),
            'onclick'=>'saveAndContinueEdit()',
            'class'=>'save'
        ),-100);

    }
    public function getHeaderText()

    {
//        return parent::getHeaderText(); // TODO: Change the autogenerated stub
        return Mage::helper('weblog')->__('My blogpost container');
    }

}
