<?php
class Dtn_Weblog_Block_Adminhtml_Blogpost_Edit_Tabs extends Mage_Adminhtml_Block_Widget_Tabs{
    public function __construct()
    {

        parent::__construct();
        $this->setId('blogpost_tabs');
        $this->setDestElementId('edit_form');
        $this->setTitle(Mage::helper('weblog')->__('Blogpost Information'));
    }
    protected function _beforeToHtml()
    {
        $this->addTab('blogpost_section', array(
            'label'     => Mage::helper('weblog')->__('Item Information'),
            'title'     => Mage::helper('weblog')->__('Item Information'),
            'content'   => $this->getLayout()->createBlock('weblog/adminhtml_form_edit_tab_form')->toHtml(),
        ));
        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }
}