<?php
//echo 'This is quan'."</br>";
$view = $this->view();

?>

<table border="solid">
    <thead>
    <th>ID</th>
    <th>Title</th>
    <th>Post</th>
    <th>Date</th>
    <th>timestamp</th>
    </thead>
     <?php foreach ($view as $key => $value) { ?>
    <tbody>
        <tr>
            <td><?php echo $key+1 ?></td>
            <td><?php echo $value->getTitle() ?></td>
            <td><?php echo $value->getPost() ?></td>
            <td><?php echo $value['data'] ?></td>
            <td><?php echo $value['timestamp'] ?></td>
        </tr>
    </tbody>
    <?php } ?>
</table>
